### ISSUE TITLE
🐛 BUG : Routes with path param can't be found

### ISSUE THREAD

**Issue by ditosoft-ianlabicani** [mackignacio/rango#3]
## Thank you for reporting an issue.

Please fill in as much of the following form as you're able.

**Describe the bug**
I created a **GET** route with path of `users/:id` and I'm trying it on Postman with path of `users/1`. I got the response below: 
```
{
    "message": "Path of users/1 is missing.",
    "status": "PathNotFound",
    "error": true
}
```

**To Reproduce**
1. Create  a route with path params of `user/:id`
2. Run rango js using command `nodemon app.ts`
3. Use Postman to send a request with path of `user/1`
4. You will get a response status of `PathNotFound`

**Expected behavior**
I am expecting to see the route to be found using path param

**Screenshots**
![image](https://github.com/mackignacio/rango/assets/91765472/81651d94-bb88-4742-8ad7-6dc9f8a8a166)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest

**Additional context**
None

**Comment by mackignacio** [comment]
Thank you. I really appreciate the effort on creating this issue.
